import { Wheat, Zap, Package } from "lucide-react";

export const CATEGORIES = [
  { id: "grocery", label: "Grocery", icon: Wheat, color: "#1E3557" },
  { id: "fmcg", label: "FMCG", icon: Package, color: "#A8471F" },
  { id: "electronics", label: "Electronics", icon: Zap, color: "#8C7A5B" },
];

export function currency(n) {
  return "₹" + Number(n || 0).toLocaleString("en-IN");
}

export const styles = {
  phoneOuter: { minHeight: "100vh", width: "100%", display: "flex", justifyContent: "center", alignItems: "flex-start", background: "#D9CDA6", padding: "24px 12px", fontFamily: "'Work Sans', sans-serif", boxSizing: "border-box" },
  phoneFrame: { width: 390, maxWidth: "100%", height: 780, maxHeight: "92vh", background: "#EDE4CE", borderRadius: 32, boxShadow: "0 20px 50px rgba(34,38,43,0.28)", display: "flex", flexDirection: "column", overflow: "hidden", position: "relative", border: "6px solid #22262B" },
  header: { background: "#1E3557", padding: "18px 18px 16px", display: "flex", justifyContent: "space-between", alignItems: "flex-start" },
  storeName: { fontFamily: "'Fraunces', serif", fontSize: 19, fontWeight: 700, color: "#EDE4CE", letterSpacing: "-0.2px" },
  locationRow: { display: "flex", alignItems: "center", gap: 4, marginTop: 4 },
  locationText: { fontSize: 11.5, color: "#C9BE9E", fontWeight: 500 },
  cartPill: { position: "relative", background: "rgba(237,228,206,0.14)", border: "1px solid rgba(237,228,206,0.3)", borderRadius: 12, width: 38, height: 38, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" },
  cartBadge: { position: "absolute", top: -5, right: -5, background: "#D9A441", color: "#22262B", fontSize: 10, fontWeight: 700, borderRadius: 20, minWidth: 16, height: 16, display: "flex", alignItems: "center", justifyContent: "center", padding: "0 3px" },
  body: { flex: 1, overflowY: "auto", padding: "14px 16px 90px" },
  searchWrap: { display: "flex", alignItems: "center", gap: 8, background: "#FFFFFF", border: "1px solid #DDD3B8", borderRadius: 12, padding: "9px 12px", marginBottom: 14 },
  searchInput: { border: "none", outline: "none", background: "transparent", fontSize: 13, color: "#22262B", width: "100%", fontFamily: "'Work Sans', sans-serif" },
  catRow: { display: "flex", gap: 8, marginBottom: 16 },
  catChip: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 6, padding: "9px 8px", borderRadius: 12, border: "1.5px solid", cursor: "pointer" },
  catChipLabel: { fontSize: 12.5, fontWeight: 600 },
  sectionLabel: { fontSize: 11, fontWeight: 700, color: "#8C7A5B", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 10 },
  grid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  card: { background: "#FFFFFF", border: "1px solid #E4DAC0", borderRadius: 14, padding: 12, position: "relative" },
  cardName: { fontSize: 13, fontWeight: 600, color: "#22262B", lineHeight: 1.25, minHeight: 33 },
  cardPriceRow: { display: "flex", alignItems: "baseline", gap: 2, margin: "6px 0 10px" },
  cardPrice: { fontFamily: "'JetBrains Mono', monospace", fontSize: 15, fontWeight: 700, color: "#1E3557" },
  cardUnit: { fontSize: 11, color: "#8C7A5B" },
  ticket: { display: "flex", alignItems: "center", justifyContent: "space-between", background: "#EDE4CE", border: "1px dashed #C9BE9E", borderRadius: 8, padding: "5px 6px" },
  ticketBtn: { width: 22, height: 22, borderRadius: 6, background: "#EDE4CE", border: "1.5px solid #1E3557", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" },
  ticketQty: { fontFamily: "'JetBrains Mono', monospace", fontSize: 11, fontWeight: 700, color: "#22262B" },
  emptyState: { gridColumn: "1 / -1", textAlign: "center", fontSize: 12.5, color: "#8C7A5B", padding: "30px 10px" },
  cartLine: { display: "flex", alignItems: "center", background: "#FFFFFF", border: "1px solid #E4DAC0", borderRadius: 12, padding: "10px 12px", marginBottom: 8 },
  cartLineName: { fontSize: 13, fontWeight: 600, color: "#22262B" },
  cartLineMeta: { fontSize: 11, color: "#8C7A5B", marginTop: 2, fontFamily: "'JetBrains Mono', monospace" },
  cartLineRight: { display: "flex", alignItems: "center", gap: 10 },
  cartLineTotal: { fontFamily: "'JetBrains Mono', monospace", fontSize: 13, fontWeight: 700, color: "#1E3557" },
  removeBtn: { width: 22, height: 22, borderRadius: 20, background: "#F3E9DC", border: "none", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" },
  totalsBox: { background: "#FFFFFF", border: "1px solid #E4DAC0", borderRadius: 12, padding: 14, marginTop: 8 },
  totalsRow: { display: "flex", justifyContent: "space-between", fontSize: 13, color: "#22262B", padding: "4px 0" },
  totalsDivider: { height: 1, background: "#E4DAC0", margin: "6px 0" },
  mono: { fontFamily: "'JetBrains Mono', monospace", fontWeight: 700 },
  emptyCart: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "70px 20px", gap: 10 },
  emptyCartText: { fontSize: 13, color: "#8C7A5B", fontWeight: 500 },
  browseBtn: { marginTop: 6, background: "#1E3557", color: "#EDE4CE", border: "none", borderRadius: 10, padding: "10px 18px", fontSize: 12.5, fontWeight: 600, cursor: "pointer" },
  placedWrap: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "70px 20px", gap: 10 },
  placedCircle: { width: 52, height: 52, borderRadius: 30, background: "#4B7A4B", display: "flex", alignItems: "center", justifyContent: "center" },
  placedTitle: { fontFamily: "'Fraunces', serif", fontSize: 18, fontWeight: 700, color: "#22262B", textAlign: "center" },
  placedSub: { fontSize: 12.5, color: "#8C7A5B", textAlign: "center" },
  placeholderTab: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "50px 30px", gap: 10, textAlign: "center" },
  placeholderText: { fontSize: 12.5, color: "#8C7A5B", lineHeight: 1.5 },
  checkoutBar: { position: "absolute", left: 16, right: 16, bottom: 78, background: "#D9A441", color: "#22262B", border: "none", borderRadius: 14, padding: "13px 18px", display: "flex", alignItems: "center", justifyContent: "space-between", fontSize: 13.5, fontWeight: 700, cursor: "pointer", boxShadow: "0 8px 20px rgba(217,164,65,0.4)" },
  viewCartBar: { position: "absolute", left: 16, right: 16, bottom: 78, background: "#1E3557", color: "#EDE4CE", border: "none", borderRadius: 14, padding: "12px 16px", display: "flex", alignItems: "center", justifyContent: "space-between", fontSize: 12.5, fontWeight: 600, cursor: "pointer", boxShadow: "0 8px 20px rgba(30,53,87,0.35)" },
  viewCartLink: { display: "flex", alignItems: "center", gap: 2, color: "#D9A441", fontWeight: 700 },
  nav: { display: "flex", borderTop: "1px solid #DDD3B8", background: "#F7F2E4", padding: "8px 6px 10px" },
  navBtn: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 3, background: "transparent", border: "none", cursor: "pointer", position: "relative", padding: "4px 0" },
  navLabel: { fontSize: 9.5 },
  navDot: { position: "absolute", top: -8, width: 4, height: 4, borderRadius: 4, background: "#D9A441" },
  toast: { position: "absolute", top: 90, left: "50%", transform: "translateX(-50%)", background: "#22262B", color: "#EDE4CE", fontSize: 12, fontWeight: 600, padding: "8px 16px", borderRadius: 20, boxShadow: "0 8px 20px rgba(0,0,0,0.25)", zIndex: 10 },
  lockWrap: { display: "flex", flexDirection: "column", alignItems: "center", padding: "50px 24px", textAlign: "center" },
  lockCircle: { width: 48, height: 48, borderRadius: 26, background: "#1E3557", display: "flex", alignItems: "center", justifyContent: "center", marginBottom: 12 },
  ownerTabs: { display: "flex", gap: 6, marginBottom: 14 },
  ownerTabBtn: { flex: 1, border: "1px solid #DDD3B8", borderRadius: 10, padding: "8px 6px", fontSize: 11.5, fontWeight: 600, cursor: "pointer" },
  orderCard: { background: "#FFFFFF", border: "1px solid #E4DAC0", borderRadius: 12, padding: 12, marginBottom: 10 },
  orderCardTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 8 },
  orderId: { fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: "#8C7A5B", fontWeight: 700 },
  statusPill: { fontSize: 10, fontWeight: 700, padding: "3px 9px", borderRadius: 20, background: "#DCE6F5", color: "#1E3557" },
  orderItemRow: { display: "flex", justifyContent: "space-between", fontSize: 12, color: "#22262B", padding: "3px 0" },
  orderTotalRow: { display: "flex", justifyContent: "space-between", fontSize: 12.5, fontWeight: 700, borderTop: "1px solid #E4DAC0", marginTop: 6, paddingTop: 6 },
  statusBtnRow: { display: "flex", gap: 5, marginTop: 10, flexWrap: "wrap" },
  statusBtn: { fontSize: 10, padding: "5px 8px", borderRadius: 8, border: "1px solid #DDD3B8", background: "#FFFFFF", color: "#22262B", cursor: "pointer" },
  statusBtnActive: { background: "#1E3557", color: "#EDE4CE", borderColor: "#1E3557" },
  productRow: { display: "flex", alignItems: "center", gap: 8, background: "#FFFFFF", border: "1px solid #E4DAC0", borderRadius: 12, padding: "10px 12px", marginBottom: 8 },
  iconBtn: { width: 28, height: 28, borderRadius: 8, border: "1px solid #DDD3B8", background: "#FFFFFF", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" },
  backBtn: { display: "flex", alignItems: "center", gap: 6, background: "none", border: "none", color: "#1E3557", fontSize: 12.5, fontWeight: 600, cursor: "pointer", marginBottom: 12, padding: 0 },
  fieldLabel: { fontSize: 11, fontWeight: 600, color: "#8C7A5B", marginBottom: 4, display: "block" },
  modalInput: { width: "100%", border: "1px solid #DDD3B8", borderRadius: 10, padding: "10px 12px", fontSize: 13, marginBottom: 10, boxSizing: "border-box", fontFamily: "'Work Sans', sans-serif" },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(34,38,43,0.45)", display: "flex", alignItems: "flex-end", justifyContent: "center", zIndex: 20 },
  modalSheet: { width: 390, maxWidth: "100%", background: "#EDE4CE", borderRadius: "20px 20px 0 0", padding: "10px 20px 24px" },
  modalHandle: { width: 36, height: 4, background: "#C9BE9E", borderRadius: 4, margin: "6px auto 14px" },
};

export function statusStyle(status) {
  const map = {
    "New": { background: "#FCEBC9", color: "#8A5A0A" },
    "Packed": { background: "#DCE6F5", color: "#1E3557" },
    "Out for delivery": { background: "#E4D9F5", color: "#5B3E8A" },
    "Delivered": { background: "#DCEEDC", color: "#2F5A2F" },
  };
  return map[status] || { background: "#EEE", color: "#22262B" };
}
